# -*- coding: utf-8 -*-
"""shadow_ranking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14RRvGePNF_oxOdmm6K1mi3Gf2DRvt1Ao
"""

import os

# define the directory structure
folders = [
    "shadow_ranking_project",
    "shadow_ranking_project/data",
    "shadow_ranking_project/src"
]


for folder in folders:
    if not os.path.exists(folder):
        os.makedirs(folder)
        print(f"created directory: {folder}")

init_path = "shadow_ranking_project/src/__init__.py"
with open(init_path, "w") as f:
    pass

explore_script_content = """# explore.py
# this file is dedicated solely to understanding data distributions and running manual sql audits
print("exploration sandbox initialized successfully.")
"""

explore_path = "shadow_ranking_project/explore.py"
with open(explore_path, "w") as f:
    f.write(explore_script_content)

print("\nworkspace setup complete.")

"""
created directory: shadow_ranking_project
created directory: shadow_ranking_project/data
created directory: shadow_ranking_project/src

workspace setup complete.
"""

"""**The SQL Schema & Data Generation Pipeline:**

We will track four core dimensions of a listing to mimic a live e-commerce ecosystem:

* Listing Metadata: Basic identifiers, price, and categorization.

* Seller Performance: History, response times, and cancellation rates.

* Customer Engagement: Click-through rates, conversion rates, and reviews.

* The Search Engine Log: The actual organic search position assigned to the listing.

**The Hidden Shadow Formula:**

To make our downstream analysis challenging and insightful, the true search position will be determined by a non-linear combination of factors:

* A high conversion rate boosts rank.

* High shipping fees or bad seller ratings exponentially penalize rank.

* The Shadow Variable: A sudden, undocumented penalty applied to sellers whose processing time exceeds 48 hours, regardless of how good their reviews are.
"""

import os

database_script_content = """# src/database.py
import duckdb
import numpy as np
import pandas as pd

def initialize_database(db_path="shadow_ranking_project/data/marketplace_data.db", num_listings=50000):
    # establish a persistent local connection to the duckdb storage file
    conn = duckdb.connect(db_path)

    # define the relational schema using clean structured data types
    conn.execute(\"\"\"
        create or replace table search_listings (
            listing_id integer primary key,
            category varchar,
            price double,
            shipping_fee double,
            historical_sales integer,
            click_through_rate double,
            conversion_rate double,
            seller_rating double,
            processing_time_hours double,
            is_promoted integer,
            organic_search_rank integer
        );
    \"\"\")

    # generate deterministic synthetic data with rich feature interaction
    np.random.seed(42)

    listing_ids = np.arange(1, num_listings + 1)
    categories = np.random.choice(["electronics", "apparel", "home_decor", "beauty", "fitness"], num_listings)
    prices = np.random.gamma(shape=3, scale=15, size=num_listings) + 5.0
    shipping_fees = np.where(np.random.rand(num_listings) > 0.4, np.random.uniform(2.0, 12.0, num_listings), 0.0)
    historical_sales = np.random.negative_binomial(n=5, p=0.01, size=num_listings)

    click_through_rate = np.random.beta(a=2, b=20, size=num_listings)
    # conversion rate is correlated naturally with click through rates
    conversion_rate = click_through_rate * np.random.uniform(0.1, 0.5, num_listings)

    seller_rating = np.clip(np.random.normal(loc=4.2, scale=0.6, size=num_listings), 1.0, 5.0)
    processing_time_hours = np.random.exponential(scale=24, size=num_listings) + 4.0
    is_promoted = np.where(np.random.rand(num_listings) > 0.85, 1, 0)

    # calculate the hidden structural ranking score (the system black box)
    # base utility score derived from empirical engagement metrics
    base_score = (historical_sales * 0.1) + (click_through_rate * 50) + (conversion_rate * 150)

    # positive or negative modifiers mirroring standard marketplace logic
    rating_modifier = (seller_rating - 3.0) * 15
    price_penalty = (prices + shipping_fees) * -0.05
    promoted_boost = is_promoted * 25

    # the hidden shadow ranking constraint: severe penalty for late processing windows
    shadow_penalty = np.where(processing_time_hours > 48.0, -80.0, 0.0)

    # inject stochastic variance to simulate unmeasured consumer behavioral noise
    system_noise = np.random.normal(loc=0.0, scale=10.0, size=num_listings)

    total_score = base_score + rating_modifier + price_penalty + promoted_boost + shadow_penalty + system_noise

    # create a dataframe to easily parse data straight into duckdb tables
    df = pd.DataFrame({
        "listing_id": listing_ids,
        "category": categories,
        "price": prices,
        "shipping_fee": shipping_fees,
        "historical_sales": historical_sales,
        "click_through_rate": click_through_rate,
        "conversion_rate": conversion_rate,
        "seller_rating": seller_rating,
        "processing_time_hours": processing_time_hours,
        "is_promoted": is_promoted,
        "score": total_score
    })

    # sort within each distinct product category to determine rank position
    df["organic_search_rank"] = df.groupby("category")["score"].rank(ascending=False, method="first").astype(int)
    df = df.drop(columns=["score"])

    # stream the completed dataset directly into our relational schema
    conn.execute("insert into search_listings select * from df")

    print(f"successfully populated relational table with {num_listings} mock engine records.")
    conn.close()

if __name__ == "__main__":
    initialize_database()
"""

# save the content into the physical script path
database_path = "shadow_ranking_project/src/database.py"
with open(database_path, "w") as f:
    f.write(database_script_content)

# reload and execute the module to physically generate the duckdb file
import sys
if "src.database" in sys.modules:
    del sys.modules["src.database"]
sys.path.append("shadow_ranking_project")
from src.database import initialize_database
initialize_database()

"""
successfully populated relational table with 50000 mock engine records.
"""

"""In this step, we will use advanced SQL window functions and aggregations inside DuckDB to look for anomalies; specifically looking at how fulfillment speeds skew ranking metrics across different categories."""

import os

explore_script_content = """# explore.py
import duckdb

def run_data_audit(db_path="shadow_ranking_project/data/marketplace_data.db"):
    # establish connection to our local relational database file
    conn = duckdb.connect(db_path)

    print("audit log 1: high level distribution summary per category ---")
    # check average metrics across different marketplace categories
    query_1 = \"\"\"
        select
            category,
            count(*) as total_items,
            round(avg(price), 2) as avg_price,
            round(avg(seller_rating), 2) as avg_seller_rating,
            round(avg(processing_time_hours), 1) as avg_processing_hours,
            round(avg(organic_search_rank), 0) as avg_assigned_rank
        from search_listings
        group by category
        order by total_items desc;
    \"\"\"
    print(conn.execute(query_1).fetch_df().to_string(index=False))

    print("\\n-audit log 2: profiling top 5 ranked listings per category ---")
    # use window partitioning to inspect the attributes of premium ranked items
    query_2 = \"\"\"
        with ranked_snapshots as (
            select
                category,
                listing_id,
                organic_search_rank,
                price,
                round(seller_rating, 2) as rating,
                round(processing_time_hours, 1) as proc_hours,
                is_promoted
            from search_listings
        )
        select * from ranked_snapshots
        where organic_search_rank <= 3
        order by category, organic_search_rank;
    \"\"\"
    print(conn.execute(query_2).fetch_df().to_string(index=False))

    print("\\naudit log 3: identifying anomalies in the top 100 spots ---")
    # search for listings with pristine seller ratings that are buried with lack of reasoning
    query_3 = \"\"\"
        select
            category,
            count(*) as buried_high_quality_sellers
        from search_listings
        where organic_search_rank > 500
          and seller_rating >= 4.5
          and processing_time_hours > 48.0
        group by category;
    \"\"\"
    print(conn.execute(query_3).fetch_df().to_string(index=False))

    conn.close()

if __name__ == "__main__":
    run_data_audit()
"""

# save the content into explore.py
explore_path = "shadow_ranking_project/explore.py"
with open(explore_path, "w") as f:
    f.write(explore_script_content)

# view the database profile logs
import sys
sys.path.append("shadow_ranking_project")
from explore import run_data_audit
run_data_audit()

"""
audit log 1: high level distribution summary per category ---
   category  total_items  avg_price  avg_seller_rating  avg_processing_hours  avg_assigned_rank
    fitness        10117      50.33               4.17                  28.9             5059.0
     beauty        10101      50.19               4.17                  27.9             5051.0
    apparel        10073      50.35               4.17                  28.3             5037.0
electronics         9924      49.68               4.17                  28.2             4963.0
 home_decor         9785      49.97               4.17                  28.0             4893.0

-audit log 2: profiling top 5 ranked listings per category ---
   category  listing_id  organic_search_rank     price  rating  proc_hours  is_promoted
    apparel       38073                    1 30.418470    3.50        36.2            1
    apparel       26776                    2 18.241261    4.53        26.2            1
    apparel       21043                    3 43.715004    4.50        16.1            0
     beauty       22931                    1 35.666292    4.05        13.5            1
     beauty       40916                    2 42.594057    4.76        21.7            0
     beauty       16370                    3 73.453808    4.05        32.2            0
electronics       14855                    1 89.168111    4.30        26.0            0
electronics       47410                    2 25.723747    4.42        13.9            1
electronics       17186                    3 28.015912    4.91        16.5            1
    fitness       46536                    1 24.636898    5.00        42.8            1
    fitness         334                    2 74.939992    4.30        17.4            1
    fitness        1580                    3 51.301520    4.55        16.2            0
 home_decor        8821                    1 19.558896    4.43        29.1            0
 home_decor       34933                    2 49.153719    4.41         8.9            0
 home_decor       44882                    3 74.539974    4.61         5.4            0

audit log 3: identifying anomalies in the top 100 spots ---
   category  buried_high_quality_sellers
     beauty                          495
electronics                          464
    fitness                          544
    apparel                          523
 home_decor                          436
"""

"""As we can see, across all five categories, we have roughly 450 to 550 sellers per category who have pristine product ratings ($\ge 4.5$) but are buried way down past rank 500.Looking back at audit log 2, we can see that every single top-3 listing has processing hours well below 48 hours (mostly ranging from 5 to 36 hours).

This is exactly how a black-box ranking system operates in the real world: the broad surface aggregates (like audit log 1) look completely normal, but a hidden conditional threshold is silently punishing high-performing accounts.

Moving on to feature engineering,

In this module, we will implement preprocessing steps:

Categorical Encoding: We will use one-hot encoding to transform the text category column into mathematical flags.

Target Definition: Since we want to reverse-engineer prominence, we will define our target variable as a binary flag: is_top_tier = 1 if the listing's search rank is within the top 15% of its category, and 0 if it is buried.

Data Partitioning: We will segment the 50,000 rows into an 80/20 train/test split to guarantee rigorous validation metrics.
"""

import os

feature_script_content = """# src/feature_engineering.py
import duckdb
import pandas as pd
from sklearn.model_selection import train_test_split

def extract_and_engineer_features(db_path="shadow_ranking_project/data/marketplace_data.db"):
    # establish connection to the database
    conn = duckdb.connect(db_path)

    # xtract all rows from search listings table into a dataframe
    query = "select * from search_listings;"
    df = conn.execute(query).fetch_df()
    conn.close()

    # define structural target variable (top 15 percent of listings within category)
    # in an engine audit, predicting premium positioning exposes visibility drivers
    df["is_top_tier"] = (df["organic_search_rank"] <= 1500).astype(int)

    # process categorical attributes using one hot encoding vectors
    df_encoded = pd.get_dummies(df, columns=["category"], drop_first=False)

    # split features and target matrices, exclude identity values
    # we explicitly drop tracking labels that would cause data leakage
    feature_columns = [col for col in df_encoded.columns if col not in [
        "listing_id", "organic_search_rank", "is_top_tier"
    ]]

    x = df_encoded[feature_columns]
    y = df_encoded["is_top_tier"]

    # 80/20 train test split
    x_train, x_test, y_train, y_test = train_test_split(
        x, y, test_size=0.20, random_state=42, stratify=y
    )

    print("feature engineering module executed.")
    print(f"training matrix shape: {x_train.shape} | testing matrix shape: {x_test.shape}")

    return x_train, x_test, y_train, y_test

if __name__ == "__main__":
    extract_and_engineer_features()
"""

feature_path = "shadow_ranking_project/src/feature_engineering.py"
with open(feature_path, "w") as f:
    f.write(feature_script_content)

# reload modules and verify processing shapes
import sys
if "src.feature_engineering" in sys.modules:
    del sys.modules["src.feature_engineering"]
sys.path.append("shadow_ranking_project")
from src.feature_engineering import extract_and_engineer_features
_ = extract_and_engineer_features()

"""
feature engineering module executed.
training matrix shape: (40000, 13) | testing matrix shape: (10000, 13)
"""

"""The data partitioning split the records exactly as intended: 40,000 baseline items to train our diagnostic estimators and 10,000 clean records reserved to calculate validation precision.

If our model can successfully predict whether a listing is in the top 15% without explicitly knowing the original scoring matrix, it means the model has successfully duplicated the engine's decision boundaries. The feature importance weights will then show us exactly which variables the engine prioritizes.
"""

import os

model_script_content = """# src/audit_model.py
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np

def train_and_audit_engine(x_train, x_test, y_train, y_test):
    print("initiating random forest audit model training...")

    # initialize the model
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=12,
        random_state=42,
        n_jobs=-1
    )

    model.fit(x_train, y_train)

    # compute target predictions on unseen validation matrix
    y_pred = model.predict(x_test)

    print("\\n--- model verification: classification matrix report ---")
    print(classification_report(y_test, y_pred, digits=4))

    # isolate feature importance weights to rank structural contributors
    importances = model.feature_importances_
    feature_names = x_train.columns

    importance_df = pd.DataFrame({
        "feature": feature_names,
        "importance_weight": importances
    }).sort_values(by="importance_weight", ascending=False)

    print("--- model verification: extracted feature importance rankings ---")
    print(importance_df.to_string(index=False))

    return model, importance_df

if __name__ == "__main__":
    import sys
    sys.path.append("shadow_ranking_project")
    from src.feature_engineering import extract_and_engineer_features
    x_tr, x_te, y_tr, y_te = extract_and_engineer_features()
    train_and_audit_engine(x_tr, x_te, y_tr, y_te)
"""

model_path = "shadow_ranking_project/src/audit_model.py"
with open(model_path, "w") as f:
    f.write(model_script_content)

import sys
if "src.audit_model" in sys.modules:
    del sys.modules["src.audit_model"]
sys.path.append("shadow_ranking_project")
from src.audit_model import train_and_audit_engine
from src.feature_engineering import extract_and_engineer_features

x_train, x_test, y_train, y_test = extract_and_engineer_features()
_, feature_rankings = train_and_audit_engine(x_train, x_test, y_train, y_test)

"""
feature engineering module executed.
training matrix shape: (40000, 13) | testing matrix shape: (10000, 13)
initiating random forest audit model training...

--- model verification: classification matrix report ---
              precision    recall  f1-score   support

           0     0.9545    0.9804    0.9673      8500
           1     0.8685    0.7353    0.7964      1500

    accuracy                         0.9436     10000
   macro avg     0.9115    0.8578    0.8818     10000
weighted avg     0.9416    0.9436    0.9416     10000

--- model verification: extracted feature importance rankings ---
              feature  importance_weight
     historical_sales           0.574108
processing_time_hours           0.116678
        seller_rating           0.080329
          is_promoted           0.079708
      conversion_rate           0.046659
   click_through_rate           0.045684
                price           0.026685
         shipping_fee           0.018657
      category_beauty           0.002376
     category_apparel           0.002371
  category_home_decor           0.002331
 category_electronics           0.002258
     category_fitness           0.002156
"""

"""The diagnostic model achieved an overall accuracy of 94.36%, meaning the marketplace ranking engine uses a highly deterministic sorting process where positioning (the upper 15% visibility window) is strictly controlled.

Inside this tier, the random forest achieved a precision of 86.85% and a recall of 73.53%, proving it can successfully map the platform's decision boundaries despite minor stochastic noise.

However, inspecting the global feature importance weights reveals a fascinating analytics paradox: `historical_sales` dominates at 57.41%, while `processing_time_hours` emerges as the second most critical split driver at 11.66%, completely outranking raw engagement metrics like conversion rate and click-through rate.

While a surface-level analyst might incorrectly conclude that sales volume is the only lever that matters, the results also expose a non-linear shadow penalty; when processing times exceed a strict 48-hour threshold, a drop-dead filter obliterates the listing's visibility score regardless of conversion excellence.

Because standard linear dependencies cannot capture this happening, the tree-based model isolates the processing variable to make structural cuts early in its decision nodes.

"""

!pip install shap

import os

explain_script_content = """# src/explainability.py
import shap
import matplotlib.pyplot as plt
import os

def generate_engine_explanations(model, x_test, output_dir="shadow_ranking_project/data"):
    print("initializing shapley dependency auditing... (calculating local feature impacts)")

    # tree explainer optimized for forest structures
    explainer = shap.TreeExplainer(model)

    # compute shap values on a representative validation sampling
    sample_size = min(1000, len(x_test))
    x_sample = x_test.sample(sample_size, random_state=42)
    shap_values = explainer(x_sample)

    # isolate the target top tier prediction array (class 1 index)
    if len(shap_values.shape) == 3:
        shap_values_target = shap_values[:, :, 1]
    else:
        shap_values_target = shap_values

    plt.figure(figsize=(8, 5))

    # relationship between processing duration and localized log odds push
    shap.plots.scatter(
        shap_values_target[:, "processing_time_hours"],
        show=False
    )

    plt.title("auditing system shadow rankings: processing time threshold impact", fontsize=11, pad=15)
    plt.xlabel("processing duration (hours)", fontsize=9)
    plt.ylabel("shap value (impact on top tier visibility probability)", fontsize=9)
    plt.axvline(x=48.0, color="red", linestyle="--", alpha=0.7, label="suspected shadow penalty threshold")
    plt.legend(frameon=True, facecolor="white", edgecolor="none")
    plt.tight_layout()

    plot_path = os.path.join(output_dir, "shadow_threshold_audit.png")
    plt.savefig(plot_path, dpi=300)
    plt.close()

    print(f"visualization saved to: {plot_path}")
    return plot_path

if __name__ == "__main__":
    import sys
    sys.path.append("shadow_ranking_project")
    from src.feature_engineering import extract_and_engineer_features
    from src.audit_model import train_and_audit_engine

    x_tr, x_te, y_tr, y_te = extract_and_engineer_features()
    fitted_model, _ = train_and_audit_engine(x_tr, x_te, y_tr, y_te)
    generate_engine_explanations(fitted_model, x_te)
"""

explain_path = "shadow_ranking_project/src/explainability.py"
with open(explain_path, "w") as f:
    f.write(explain_script_content)

# execute explainability module over the generated framework items
import sys
if "src.explainability" in sys.modules:
    del sys.modules["src.explainability"]
sys.path.append("shadow_ranking_project")
from src.explainability import generate_engine_explanations

# ensure the model variable from step 5 is accurately referenced
if 'fitted_model' not in locals():
    from src.feature_engineering import extract_and_engineer_features
    from src.audit_model import train_and_audit_engine
    x_train, x_test, y_train, y_test = extract_and_engineer_features()
    fitted_model, _ = train_and_audit_engine(x_train, x_test, y_train, y_test)

# calculate shap plot attributes using verified local variables
_ = generate_engine_explanations(fitted_model, x_test)

"""
 feature engineering module executed.
training matrix shape: (40000, 13) | testing matrix shape: (10000, 13)
initiating random forest audit model training...

--- model verification: classification matrix report ---
              precision    recall  f1-score   support

           0     0.9545    0.9804    0.9673      8500
           1     0.8685    0.7353    0.7964      1500

    accuracy                         0.9436     10000
   macro avg     0.9115    0.8578    0.8818     10000
weighted avg     0.9416    0.9436    0.9416     10000

--- model verification: extracted feature importance rankings ---
              feature  importance_weight
     historical_sales           0.574108
processing_time_hours           0.116678
        seller_rating           0.080329
          is_promoted           0.079708
      conversion_rate           0.046659
   click_through_rate           0.045684
                price           0.026685
         shipping_fee           0.018657
      category_beauty           0.002376
     category_apparel           0.002371
  category_home_decor           0.002331
 category_electronics           0.002258
     category_fitness           0.002156
initializing shapley dependency auditing... (calculating local feature impacts)
visualization saved to: shadow_ranking_project/data/shadow_threshold_audit.png
<Figure size 800x500 with 0 Axes>
"""

"""Look at how the data behaves on either side of the dashed line. between 0 and 48 hours, the shap values are clustered tightly above 0.0, showing a stable, mildly positive contribution to a listing's visibility probability.

The second a listing crosses the strict 48-hour mark, the shapley values experience a vertical drop down into deep negative territory (dropping straight to -0.1 and scattering down to -0.4). this extreme cliff is the mathematical signature of a non-linear shadow penalty; it shows the exact point where fulfillment speed transitions from a minor optimization variable to a dominant filter.
"""

import os

main_script_content = """# main.py
import sys
import os

# append the project root directory path
sys.path.append(os.path.abspath(os.path.dirname(__file__)))

from src.database import initialize_database
from src.feature_engineering import extract_and_engineer_features
from src.audit_model import train_and_audit_engine
from src.explainability import generate_engine_explanations

def run_system_audit_pipeline():
    print("starting...")

    # database verification and row generation pipeline phase
    db_path = "shadow_ranking_project/data/marketplace_data.db"
    if not os.path.exists(db_path):
        print("local database storage file not discovered. initializing fallback...")
        initialize_database(db_path=db_path)
    else:
        print(f"verified database instance at connection endpoint: {db_path}")

    # extract records and execute training matrix transformations
    x_train, x_test, y_train, y_test = extract_and_engineer_features(db_path=db_path)

    # execute forest model training loops and extract global score arrays
    fitted_model, feature_rankings = train_and_audit_engine(x_train, x_test, y_train, y_test)

    # calculate localized game theoretic impact metrics and export plot visual
    plot_output_path = generate_engine_explanations(fitted_model, x_test)

    print("algorithmic shadow ranking pipeline completed")

if __name__ == "__main__":
    run_system_audit_pipeline()
"""

main_path = "shadow_ranking_project/main.py"
with open(main_path, "w") as f:
    f.write(main_script_content)

import subprocess
print("triggering system test execution of main.py via shell connector...\\n")
result = subprocess.run(["python", "shadow_ranking_project/main.py"], capture_output=True, text=True)
print(result.stdout)
if result.stderr:
    print("execution warning logs captured:")
    print(result.stderr)

"""
triggering system test execution of main.py via shell connector...\n
starting...
verified database instance at connection endpoint: shadow_ranking_project/data/marketplace_data.db
feature engineering module executed.
training matrix shape: (40000, 13) | testing matrix shape: (10000, 13)
initiating random forest audit model training...

--- model verification: classification matrix report ---
              precision    recall  f1-score   support

           0     0.9545    0.9804    0.9673      8500
           1     0.8685    0.7353    0.7964      1500

    accuracy                         0.9436     10000
   macro avg     0.9115    0.8578    0.8818     10000
weighted avg     0.9416    0.9436    0.9416     10000

--- model verification: extracted feature importance rankings ---
              feature  importance_weight
     historical_sales           0.574108
processing_time_hours           0.116678
        seller_rating           0.080329
          is_promoted           0.079708
      conversion_rate           0.046659
   click_through_rate           0.045684
                price           0.026685
         shipping_fee           0.018657
      category_beauty           0.002376
     category_apparel           0.002371
  category_home_decor           0.002331
 category_electronics           0.002258
     category_fitness           0.002156
initializing shapley dependency auditing... (calculating local feature impacts)
visualization saved to: shadow_ranking_project/data/shadow_threshold_audit.png
algorithmic shadow ranking pipeline completed

"""

"""To protect Google Colab free tier RAM from crashing from massive file downloads and multi-table relational joins, this pipeline uses a strategy called statistical parameter mirroring instead of directly loading raw Kaggle CSV files.

Rather than importing megabytes of raw text, we extracted the underlying mathematical properties of the Olist Brazilian E-Commerce dataset—such as its heavily skewed, fat-tailed lognormal pricing distribution, specific categorical transaction frequencies, and exponential logistics fulfillment lags—and embedded those exact structural metrics straight into our the generator.

This architectural design choice ensures that the data matrices behave exactly like messy, real-world market ecosystems with high behavioral variance.

This block will perform the following actions in sequence:

* Overwrite src/database.py with new, real-world parameterized schemas.

* Delete the old database file.

* Automatically execute the database initialization function to spin up the new data structure.
"""

import os
import sys
import subprocess

#overwrite src/database.py to match real world dataset distribution logic
database_script_content = """# src/database.py
import duckdb
import numpy as np
import pandas as pd

def initialize_database(db_path="shadow_ranking_project/data/marketplace_data.db", num_listings=50000):
    # establish a persistent local connection to the duckdb storage file
    conn = duckdb.connect(db_path)

    # define the relational schema
    conn.execute(\"\"\"
        create or replace table search_listings (
            listing_id integer primary key,
            category varchar,
            price double,
            shipping_fee double,
            historical_sales integer,
            click_through_rate double,
            conversion_rate double,
            seller_rating double,
            processing_time_hours double,
            is_promoted integer,
            organic_search_rank integer
        );
    \"\"\")

    np.random.seed(42)

    # establish authentic categories matching public marketplace logs
    listing_ids = np.arange(1, num_listings + 1)
    real_categories = ["health_beauty", "computers_accessories", "watches_gifts", "sports_leisure", "auto"]
    categories = np.random.choice(real_categories, num_listings, p=[0.25, 0.20, 0.15, 0.22, 0.18])

    # simulate high variance lognormal pricing arrays matching olist metrics
    prices = np.random.lognormal(mean=4.1, sigma=0.8, size=num_listings) + 2.0
    prices = np.clip(prices, 5.0, 800.0)

    # shipping values are heavily linked to pricing thresholds in authentic marketplaces
    shipping_fees = np.where(prices > 150.0, 0.0, np.random.uniform(5.0, 35.0, num_listings))

    # populate authentic historical sales distributions using discrete negative binomial counts
    historical_sales = np.random.negative_binomial(n=2, p=0.005, size=num_listings)

    click_through_rate = np.random.beta(a=1.5, b=25, size=num_listings)
    conversion_rate = click_through_rate * np.random.uniform(0.05, 0.45, num_listings)

    # build realistic highly skewed ratings reflecting real e commerce reviews
    seller_rating = np.random.choice(
        [5.0, 4.0, 3.0, 2.0, 1.0],
        num_listings,
        p=[0.55, 0.25, 0.10, 0.04, 0.06]
    ) + np.random.uniform(-0.3, 0.0, num_listings)
    seller_rating = np.clip(seller_rating, 1.0, 5.0)

    # fulfillment logistics processing times reflecting real global shipping windows
    processing_time_hours = np.random.exponential(scale=30, size=num_listings) + 2.0
    is_promoted = np.where(np.random.rand(num_listings) > 0.88, 1, 0)

    # calculate the hidden search engine score matrix
    base_score = (historical_sales * 0.15) + (click_through_rate * 40) + (conversion_rate * 200)
    rating_modifier = (seller_rating - 3.0) * 20
    price_penalty = (prices + shipping_fees) * -0.02
    promoted_boost = is_promoted * 30

    # system shadow ranking drop dead constraint logic
    shadow_penalty = np.where(processing_time_hours > 48.0, -95.0, 0.0)
    system_noise = np.random.normal(loc=0.0, scale=12.0, size=num_listings)

    total_score = base_score + rating_modifier + price_penalty + promoted_boost + shadow_penalty + system_noise

    df = pd.DataFrame({
        "listing_id": listing_ids,
        "category": categories,
        "price": prices,
        "shipping_fee": shipping_fees,
        "historical_sales": historical_sales,
        "click_through_rate": click_through_rate,
        "conversion_rate": conversion_rate,
        "seller_rating": seller_rating,
        "processing_time_hours": processing_time_hours,
        "is_promoted": is_promoted,
        "score": total_score
    })

    # organize ranks dynamically partitioned within real world product segments
    df["organic_search_rank"] = df.groupby("category")["score"].rank(ascending=False, method="first").astype(int)
    df = df.drop(columns=["score"])

    conn.execute("insert into search_listings select * from df")
    print(f"successfully populated relational table with {num_listings} real world distribution profiles.")
    conn.close()

if __name__ == "__main__":
    initialize_database()
"""

# save code updates to src directory
database_path = "shadow_ranking_project/src/database.py"
with open(database_path, "w") as f:
    f.write(database_script_content)

print("src/database.py has been updated with real-world distribution profiles.")

# wipe previous database file
db_file = "shadow_ranking_project/data/marketplace_data.db"
if os.path.exists(db_file):
    os.remove(db_file)
    print("removed successfully.")

# force a hard reload of modules
for module in list(sys.modules.keys()):
    if module.startswith("src."):
        del sys.modules[module]

# append workspace paths
sys.path.append(os.path.abspath("shadow_ranking_project"))
from src.database import initialize_database
from src.feature_engineering import extract_and_engineer_features
from src.audit_model import train_and_audit_engine
from src.explainability import generate_engine_explanations

print("\n3. kicking off full pipeline...")

initialize_database(db_path=db_file)

x_train, x_test, y_train, y_test = extract_and_engineer_features(db_path=db_file)

fitted_model, feature_rankings = train_and_audit_engine(x_train, x_test, y_train, y_test)

plot_output_path = generate_engine_explanations(fitted_model, x_test)

print("==================================================================")
print("real world data pipeline integration test completed successfully.")

"""
 src/database.py has been updated with real-world distribution profiles.
removed successfully.

3. kicking off full pipeline...
successfully populated relational table with 50000 real world distribution profiles.
feature engineering module executed.
training matrix shape: (40000, 13) | testing matrix shape: (10000, 13)
initiating random forest audit model training...

--- model verification: classification matrix report ---
              precision    recall  f1-score   support

           0     0.9708    0.9846    0.9776      8500
           1     0.9050    0.8320    0.8670      1500

    accuracy                         0.9617     10000
   macro avg     0.9379    0.9083    0.9223     10000
weighted avg     0.9609    0.9617    0.9610     10000

--- model verification: extracted feature importance rankings ---
                       feature  importance_weight
              historical_sales           0.658560
         processing_time_hours           0.120903
                 seller_rating           0.095430
                   is_promoted           0.028063
               conversion_rate           0.023161
            click_through_rate           0.021753
                         price           0.018360
                  shipping_fee           0.015782
        category_watches_gifts           0.007200
        category_health_beauty           0.005500
       category_sports_leisure           0.002066
                 category_auto           0.001766
category_computers_accessories           0.001455
initializing shapley dependency auditing... (calculating local feature impacts)
visualization saved to: shadow_ranking_project/data/shadow_threshold_audit.png
==================================================================
real world data pipeline integration test completed successfully.
<Figure size 800x500 with 0 Axes>
"""

import os

stats_script_content = """# src/statistical_audit.py
import duckdb
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import os

def perform_statistical_audit(db_path="shadow_ranking_project/data/marketplace_data.db", output_dir="shadow_ranking_project/data"):
    print("initiating formal mathematical and statistical audit...")

    # establish database connection and pull target tracking variables
    conn = duckdb.connect(db_path)
    query = "select organic_search_rank, processing_time_hours, seller_rating from search_listings;"
    df = conn.execute(query).fetch_df()
    conn.close()

    # segment data into pre threshold and post threshold processing windows
    under_48 = df[df["processing_time_hours"] <= 48.0]["organic_search_rank"]
    over_48 = df[df["processing_time_hours"] > 48.0]["organic_search_rank"]

    print("\\n--- statistical validation: two sample welch t test ---")
    # execute welchs t test to account for unequal sample sizes and variances
    t_stat, p_val = stats.ttest_ind(under_48, over_48, equal_var=False)
    print(f"calculated t-statistic: {t_stat:.4f}")
    print(f"empirical p-value: {p_val:.4e} (significance threshold alpha = 0.01)")


    plt.figure(figsize=(9, 5))

    # plot the kernel density or histogram distribution for compliant vs late windows
    plt.hist(under_48, bins=50, alpha=0.6, label="compliant processing window (<= 48h)", color="#1f77b4", density=True)
    plt.hist(over_48, bins=50, alpha=0.6, label="penalized shadow window (> 48h)", color="#d62728", density=True)

    plt.title("audit distribution plot: systemic rank displacement profile", fontsize=11, pad=15)
    plt.xlabel("assigned organic search rank (lower position number implies top visibility)", fontsize=9)
    plt.ylabel("probability density profile", fontsize=9)
    plt.legend(frameon=True, facecolor="white", edgecolor="none")
    plt.tight_layout()

    plot_path = os.path.join(output_dir, "distributional_rank_audit.png")
    plt.savefig(plot_path, dpi=300)
    plt.close()

    print(f"\\ndistributional plot generated successfully. saved to: {plot_path}")
    return t_stat, p_val

if __name__ == "__main__":
    import sys
    sys.path.append("shadow_ranking_project")
    perform_statistical_audit()
"""

stats_path = "shadow_ranking_project/src/statistical_audit.py"
with open(stats_path, "w") as f:
    f.write(stats_script_content)

import sys
if "src.statistical_audit" in sys.modules:
    del sys.modules["src.statistical_audit"]
sys.path.append("shadow_ranking_project")
from src.statistical_audit import perform_statistical_audit
_ = perform_statistical_audit()

"""While global feature importance matrices heavily favor `historical_sales` as the primary driver at 65.85%, executing a two-sample Welch’s t-test exposes a  t-statistic of -159.5563 ($p = 0.0000e+00$), revealing that the entire listing population undergoes a radical, non-random structural displacement the moment fulfillment delays cross the 48-hour threshold.

This systemic rank degradation is visually validated by our empirical density distribution plot, which maps out an separation where late-processing listings are systematically blocked from high-visibility territory and compressed into the lowest exposure brackets.

By combining SHAP dependency curves with piece-wise hypothesis testing, the audit conclusively uncovers a non-linear penalty constraint that suppresses merchant visibility regardless of conversion excellence.
"""

import os

discovery_script_content = """# discover_threshold.py
import duckdb
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import os

def run_automated_threshold_discovery():
    print("starting automated black-box discovery")

    db_path = "shadow_ranking_project/data/marketplace_data.db"
    output_dir = "shadow_ranking_project/data"

    # initialize database connection and fetch target arrays
    conn = duckdb.connect(db_path)
    query = "select organic_search_rank, processing_time_hours from search_listings;"
    df = conn.execute(query).fetch_df()
    conn.close()

    # define candidate search space thresholds
    candidate_thresholds = np.arange(12, 86, 2)
    effect_sizes = []

    print("sweeping processing latency windows and calculating cohen's d effect sizes...")

    for cutoff in candidate_thresholds:
        under_split = df[df["processing_time_hours"] <= cutoff]["organic_search_rank"]
        over_split = df[df["processing_time_hours"] > cutoff]["organic_search_rank"]

        if len(under_split) < 100 or len(over_split) < 100:
            effect_sizes.append(0.0)
            continue

        # compute cohen's d to quantify population separation magnitude
        mean_diff = under_split.mean() - over_split.mean()
        pooled_sd = np.sqrt((under_split.var() + over_split.var()) / 2.0)
        cohens_d = mean_diff / pooled_sd
        effect_sizes.append(abs(cohens_d))

    # locate the threshold that maximizes population variance
    optimal_idx = np.argmax(effect_sizes)
    discovered_hours = candidate_thresholds[optimal_idx]
    peak_effect_size = effect_sizes[optimal_idx]

    print("\\n--- discovery report ---")
    print(f"identified system fracture point: {discovered_hours} hours latency")
    print(f"maximal practical effect size (cohen's d): {peak_effect_size:.2f}")

    # execute conditional verification checks at the optimal split node
    under_final = df[df["processing_time_hours"] <= discovered_hours]["organic_search_rank"]
    over_final = df[df["processing_time_hours"] > discovered_hours]["organic_search_rank"]

    t_stat, p_val = stats.ttest_ind(under_final, over_final, equal_var=False)
    print(f"welch's t-statistic at discovery point: {t_stat:.4f}")
    print(f"empirical p-value profile: {p_val:.4e}")

    # plot empirical density distributions at the discovered cutoff
    plt.figure(figsize=(9, 5))
    plt.hist(under_final, bins=50, alpha=0.6, label=f"compliant window (<={discovered_hours}h)", color="#1f77b4", density=True)
    plt.hist(over_final, bins=50, alpha=0.6, label=f"penalized shadow window (>{discovered_hours}h)", color="#d62728", density=True)

    plt.title(f"systemic rank displacement profile (discovered cutoff: {discovered_hours}h | d = {peak_effect_size:.2f})", fontsize=11, pad=15)
    plt.xlabel("assigned organic search rank (lower position number implies top visibility)", fontsize=9)
    plt.ylabel("probability density profile", fontsize=9)
    plt.legend(frameon=True, facecolor="white", edgecolor="none")
    plt.tight_layout()

    plot_path = os.path.join(output_dir, "discovered_change_point_audit.png")
    plt.savefig(plot_path, dpi=300)
    plt.close()

    print(f"\\nstatistical validation complete")

if __name__ == "__main__":
    run_automated_threshold_discovery()
"""

discovery_path = "shadow_ranking_project/discover_threshold.py"
with open(discovery_path, "w") as f:
    f.write(discovery_script_content)

import subprocess
result = subprocess.run(["python", "shadow_ranking_project/discover_threshold.py"], capture_output=True, text=True)
print(result.stdout)
if result.stderr:
    print("logs:", result.stderr)

"""
starting automated black-box discovery
sweeping processing latency windows and calculating cohen's d effect sizes...

--- discovery report ---
identified system fracture point: 48 hours latency
maximal practical effect size (cohen's d): 1.68
welch's t-statistic at discovery point: -159.5563
empirical p-value profile: 0.0000e+00

statistical validation complete

"""

"""The standalone discovery script above executed a data-driven brute-force grid sweep across candidate latency windows (from 12 to 84 hours in 2-hour increments), tracking the population variance at each partition point without any prior knowledge of the platform's constraints.

By calculating Cohen’s $d$ at each operational step, the algorithm localized the system fracture point at exactly **48 hours**, where the distance between the distribution means reached its absolute maximum with a monumental practical effect size of **$d = 1.68$** (well above the standard $0.8$ threshold for a large effect).

The accompanying visual histogram maps this structural cliff: the compliant listings ($\le 48\text{h}$, blue) maintain a high-density, uniform distribution anchored in premium, high-visibility ranks, while crossing the discovered threshold triggers a catastrophic population displacement that shifts the penalized listings ($> 48\text{h}$, red) deep into the lower exposure brackets ($6,000$ to $12,000$).

Backed by a Welch's $t$-statistic of **$-159.56$** and an empirical $p$-value of **$0.0000e+00$**, this independent analysis formally proves that the ranking drop is not a statistical artifact of large sample sizes, but an explicit, highly disruptive system regime shift.
"""